import java.util.Scanner;
public class RPSgame {
    public static void main(String[]args){
        //Algorithm (RSP = Rock Paper Scissor)
        //1. Ask user for input of RPS as integer
        //2. Math random numbers from 1-3 for value of computer's RPS
        //3. check and implement the game rules 
        System.out.println("****ROCK, PAPER, SCISSORS GAME*****");
        System.out.println("===================================");
         //Scanner Input from the Player.
         Scanner input = new Scanner(System.in);
           System.out.println("Enter a move!");
           System.out.print("Rock (1), Paper (2), Scissors (3): ");
           int choice = input.nextInt();
         input.close();
         if (choice == 1){
            System.out.print("You have selected Rock, ");
         }
         else if (choice == 2){
            System.out.print("You have selected Paper, ");
         }
         else if (choice == 3){
            System.out.print("You have selected Scissors, ");
         }
         else{
            System.out.print("Not a Valid move! Exiting Program.");
            System.exit(0);//end the program
         }
        
         //Random plays generated by the computer.
         int rps= (int)(1+ Math.random()*3);
         //System.out.println(rps);(used to check)
         //Assign RPS to random computer generation
         if (rps == 1){
            System.out.print("CPU has selected Rock.");
         }
         else if (rps == 2){
            System.out.print("CPU has selected Paper.");
         }
         else if (rps == 1){
            System.out.print("CPU has selected Scissors.");
         }
         

         //Now implement the game rules
         if (choice == rps){
            System.out.println("It's a tie.");
         }
         else if (choice == 1 && rps == 2){
            System.out.println("CPU wins!");
         }
         else if (choice == 1 && rps == 3){
            System.out.println("You win!");
         }
         else if (choice == 2 && rps == 1){
            System.out.print("You win!");
         }
         else if (choice == 2 && rps == 3){
            System.out.println("CPU wins!");
         }
         else if (choice == 3 && rps == 1){
            System.out.println("CPU wins");
         }
         else if (choice == 3 && rps == 2){
            System.out.println("You win");
         }
    }
}
